### ISSUE TITLE
Templating does not work

### ISSUE THREAD

**Issue by mtymek** [ezimuel/zend-stratigility-skeleton#1]
Current dev-master of skeleton is unusable - after opening in the browser it returns HTTP 200, but nothing is rendered - page is empty.

![image](https://cloud.githubusercontent.com/assets/777893/8397894/7ac4e906-1ddb-11e5-97f6-9f0d9b71c003.png)

**Comment by ezimuel** [comment]
@mtymek now the template is working, thanks to @codeliner.
