### ISSUE TITLE
Composer.lock should not be versioned

### ISSUE THREAD

**Issue by jguittard** [ezimuel/zend-stratigility-skeleton#5]

**Comment by codeliner** [comment]
@jguittard composer.lock is included in the zend-skeleton too. Reasoning can be found here: https://github.com/zendframework/ZendSkeletonApplication/pull/240

**Comment by ezimuel** [comment]
@jguittard, as reported by @codeliner we already discussed this. To summarize: in skeleton app we will include it but not in component repo.
